// Default site copy. Used to seed the settings table on first run and as a
// fallback merge target so the site never breaks if a field is missing.
module.exports = {
  site: {
    favicon: '',
    brand_name: 'MoonStar Studio',
    footer_tagline: "Web Designer & Developer. Modern websites and digital solutions for businesses, from concept to launch.",
    copyright_name: 'MoonStar Studio',
    email: 'moonstarstudio.co@gmail.com',
    phone: '+855 85 887 688',
    location: 'Cambodia',
    tiktok_url: 'https://www.tiktok.com/@moonstarstudio.co',
    facebook_url: 'https://www.facebook.com/share/17haycQPn3/',
    instagram_url: 'https://www.instagram.com/moonstar.studio.co',
  },
  home: {
    hero_image: '',
    hero_eyebrow: '// moonstar studio',
    hero_headline: 'Modern Websites That Help Your Business Grow',
    hero_tagline: 'I design and develop high-performing websites that build trust, attract customers, and turn ideas into engaging online experiences.',
    hero_btn_primary_text: 'View My Work',
    hero_btn_primary_href: '/websites',
    hero_btn_secondary_text: 'Get In Touch',
    hero_btn_secondary_href: '/contact',
    service_1_title: 'Web Design',
    service_1_desc: 'Designing clean, modern, and user-friendly websites that reflect your brand and connect with your audience.',
    service_2_title: 'UI / UX Design',
    service_2_desc: 'Creating intuitive and engaging digital experiences that make it easy for visitors to explore, understand, and take action.',
    service_3_title: 'Web Development',
    service_3_desc: 'Building fast, responsive, and fully functional websites optimized for performance on every device.',
    featured_intro: 'Explore some of my recent website projects — each one designed with creativity, performance, and user experience in mind.',
    stat_1_value: '17+',
    stat_1_label: 'projects delivered',
    stat_2_value: '12',
    stat_2_label: 'live websites',
    stat_3_value: '500',
    stat_3_label: 'cups of coffee',
    cta_heading: 'Ready to build your online presence?',
    cta_text: "Let's create a website that works as hard as you do.",
    cta_btn_text: 'Start Your Project',
  },
  about: {
    intro_heading: "Hi, I'm Moon",
    intro_text: "I'm a web designer and developer based in Cambodia. From business websites and landing pages to custom digital solutions, I craft every project with a focus on clean design, responsive layouts, and attention to every detail.",
    who_heading: 'Designer & Developer.',
    who_p1: "I'm a web designer and developer passionate about creating modern, high-performing websites that help businesses build trust, attract customers, and grow online. Every project is crafted with a focus on design, functionality, and user experience.",
    who_p2: 'I specialize in designing and developing modern websites that combine creativity, performance, and user experience. My goal is to help businesses build a strong online presence through thoughtful design and reliable development.',
    who_p3: 'From business websites and landing pages to custom digital solutions, I transform ideas into engaging online experiences with clean design, responsive layouts, and attention to every detail.',
    journey_intro: "My journey into web design and development began with a passion for creating digital experiences. Through years of learning, experimentation, and real client projects, I've developed the skills to transform ideas into professional websites.",
    journey_1_date: '2020 – 2024',
    journey_1_title: 'Degree in Information Technology & Management',
    journey_1_desc: 'Built a strong foundation in programming, database management, networking, UI/UX design, and project management while completing various academic and practical projects.',
    journey_2_date: '2024 – Present',
    journey_2_title: 'Professional Web Designer & Developer',
    journey_2_desc: 'Specializing in responsive website design, Wix Studio development, branding, SEO optimization, and custom business websites for clients across different industries.',
    expertise_intro: 'I combine creativity with technical expertise to design websites that are visually engaging, responsive, and built for performance. Every project focuses on delivering an exceptional user experience while helping businesses grow online.',
    expertise_1_title: 'Web Design',
    expertise_1_desc: 'Clean, modern, user-friendly websites.',
    expertise_2_title: 'UI / UX Design',
    expertise_2_desc: 'Intuitive, engaging digital experiences.',
    expertise_3_title: 'Web Development',
    expertise_3_desc: 'Fast, responsive, functional websites.',
    expertise_4_title: 'Wix Studio Development',
    expertise_4_desc: 'Custom business websites built on Wix Studio.',
    expertise_5_title: 'Branding',
    expertise_5_desc: 'Cohesive visual identity across every page.',
    expertise_6_title: 'SEO Optimization',
    expertise_6_desc: 'Websites structured to be found on search engines.',
    exp_1_date: '2026 – Present',
    exp_1_title: 'Founder — MoonStar Studio',
    exp_1_desc: 'Leading website design and development projects, managing client communications, and delivering complete digital solutions from concept to launch.',
    exp_2_date: '2023 – 2025',
    exp_2_title: 'Web Designer & Developer',
    exp_2_desc: 'Developed custom business websites using Wix Studio, optimized performance, and implemented responsive designs.',
    exp_3_date: '2022 – 2023',
    exp_3_title: 'Junior Web Designer',
    exp_3_desc: 'Designed responsive websites, created UI layouts, and collaborated with clients to deliver modern web solutions.',
  },
  services: {
    intro: 'Complete digital solutions — from concept to launch.',
    svc_1_title: 'Web Design',
    svc_1_desc: 'Your website is often the first impression customers have of your business. I design clean, modern layouts that reflect your brand identity, guide visitors naturally through your content, and make you look professional from the first click.',
    svc_1_list: 'Custom page layouts, Brand-aligned visual design, Mobile-first responsive design, Image and content styling',
    svc_2_title: 'UI / UX Design',
    svc_2_desc: "Great design isn't just about looking good — it's about how it feels to use. I create intuitive user interfaces and smooth user experiences so your visitors can find what they need, trust what they see, and take action easily.",
    svc_2_list: 'User flow planning, Wireframes and prototypes, Intuitive navigation structure, Conversion-focused layouts',
    svc_3_title: 'Web Development',
    svc_3_desc: 'A beautiful design needs solid development behind it. I build fast, responsive, fully functional websites — optimized for performance, tested across devices, and ready to grow with your business.',
    svc_3_list: 'Wix Studio development, Responsive implementation, Performance optimization, SEO-friendly structure, Forms and integrations',
    step_1_title: 'Discover',
    step_1_desc: 'We discuss your goals, audience, and vision for the project.',
    step_2_title: 'Design',
    step_2_desc: 'I create the visual concept and layout for your approval.',
    step_3_title: 'Develop',
    step_3_desc: 'I build the site with clean, responsive, optimized development.',
    step_4_title: 'Launch',
    step_4_desc: 'Final testing, refinements, and go-live — from concept to launch.',
    cta_heading: 'Ready to build your online presence?',
    cta_text: "Let's create a website that works as hard as you do.",
  },
  contact: {
    heading: "Let's Work Together",
    intro: "Have a project in mind? Whether you need a brand-new website or want to refresh your current one, I'd love to hear about it. Tell me about your business and your goals, and I'll get back to you with how we can bring it to life.",
    form_success_message: "Thank you so much! Your message has been sent — I'll get back to you soon.",
  },
  work: {
    heading: 'Project Portfolio',
    intro: "Explore some of my recent website projects, each designed with creativity, performance, and user experience in mind. Filter by tech to find what you're looking for.",
  },
  freelance: {
    heading: 'Need More Than a Website?',
    intro: "I work with a trusted network of freelancers for services outside my core focus — tell me what you need and I'll connect you with the right person. One point of contact, no hunting around.",
    svc_1_title: 'Photography & Photoshoots',
    svc_1_desc: 'Product shots, portraits, and branded photoshoots for your business.',
    svc_2_title: 'Poster & Graphic Design',
    svc_2_desc: 'Eye-catching posters, flyers, and print-ready graphic design.',
    svc_3_title: 'Content Marketing',
    svc_3_desc: 'Social media content, copywriting, and marketing strategy.',
    svc_4_title: 'Video Editing',
    svc_4_desc: 'Promo videos, social clips, and polished video edits.',
    svc_5_title: 'Event Photography',
    svc_5_desc: 'Coverage for launches, grand openings, and company events.',
    cta_heading: 'Have a project in mind?',
    cta_text: "Tell me what you need and I'll connect you with the right freelancer.",
  },
};
